export const STATES = {
  LOBBY: 'LOBBY',
  CATEGORY_VOTE: 'CATEGORY_VOTE',
  QUESTION_INTRO: 'QUESTION_INTRO',
  QUESTION_ACTIVE: 'QUESTION_ACTIVE',
  QUESTION_RESULT: 'QUESTION_RESULT',
  SCOREBOARD: 'SCOREBOARD',
  FINAL_PYRAMID: 'FINAL_PYRAMID',
  GAME_OVER: 'GAME_OVER',
};
