export const STATES = {
  LOBBY: 'LOBBY',
  CATEGORY_VOTE: 'CATEGORY_VOTE',
  QUESTION_INTRO: 'QUESTION_INTRO',
  QUESTION_ACTIVE: 'QUESTION_ACTIVE',
  QUESTION_RESULT: 'QUESTION_RESULT',
  SCOREBOARD: 'SCOREBOARD',
  PYRAMID_INTRO: 'PYRAMID_INTRO',
  FINAL_PYRAMID: 'FINAL_PYRAMID',
  PYRAMID_RESULT: 'PYRAMID_RESULT',
  PYRAMID_SCOREBOARD: 'PYRAMID_SCOREBOARD',
  GAME_OVER: 'GAME_OVER',
};
